name: ML Kit Vision iOS Example

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd ios/quickstarts/vision
          ls -lh
          pod install
      - name: List All Scheme
        run: |
          cd ios/quickstarts/vision
          ls -lh
          xcodebuild -project VisionExample.xcodeproj -list
      - name: Build project
        run: |
          cd ios/quickstarts/vision
          ls -lh
          xcodebuild -project VisionExample.xcodeproj -scheme VisionExample -configuration Debug -sdk iphonesimulator build-for-testing
