name: ML Kit Vision iOS Example

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: ChangeDir
        run: |
          cd ios/quickstarts/vision
      - name: Install dependencies
        run: |
          pod install
      - name: Build project
        run: |
          xcodebuild -project VisionExample.xcodeproj -scheme MLKitVisionExample -configuration Debug -destination platform=iOS Simulator,name=iPhone 13 Pro Max
